openapi: 3.0.0
info:
  title: api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /user:
    post:
      summary: Create New User
      operationId: create-user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
  /users:
    get:
      summary: List Users
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsersResponse'
      operationId: get-users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetUsersRequest'
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        email:
          type: string
          format: email
        name:
          type: string
      required:
        - id
        - email
    CreateUserRequest:
      title: CreateUserRequest
      type: object
      properties:
        name:
          type: string
        email:
          type: string
    CreateUserResponse:
      title: CreateUserResponse
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
    GetUsersRequest:
      title: GetUsersRequest
      type: object
    GetUsersResponse:
      title: GetUsersResponse
      type: array
      items:
        $ref: '#/components/schemas/User'
  responses: {}
